# Generated by Django 5.1.3 on 2024-11-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twtcloneapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='nama',
            new_name='username',
        ),
    ]
