# Generated by Django 5.1.3 on 2024-11-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twtcloneapp', '0004_remove_data_user_alter_data_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
